### ISSUE TITLE
Product IS not starting up on AWS

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#559]
**Description:**

IS is not starting up on AWS. This was tested with IS 5.4.0 both on TestGrid and through manually running the cloudformation script on AWS CLI.

**Suggested Labels:**

Type/Bug, Severity/Critical, Priority/Highest

**Suggested Assignees:**
AsmaJ

**Comment by azinneera** [comment]
This should be resolved by the IAM team. Hence raised the issue to them.

**Comment by harshanL** [comment]
I've raised an issue [1] in "cloudformation-is" repo. For now, we can use the scripts available in my fork which uses a shell script to do the deployment.
 
[1]. https://github.com/wso2/cloudformation-is/issues/21 
[2]. https://github.com/harshanl/cloudformation-is

**Comment by harshanL** [comment]
The issue in cloudformation-is repo is not yet fixed. Hence moving to the next milestone.

**Comment by harshanL** [comment]
Verified the scripts manually.
